### ISSUE TITLE
node web framework research

### ISSUE THREAD

**Issue by zhyq0826** [zhyq0826/zhyq0826.github.io#5]
## [sailsjs](http://sailsjs.org/)

**feature**
- MVC web framework
- based on [express](http://expressjs.com/), [socket.io](http://socket.io/)
- data-driven api(auto-generated), service-oriented architecture
- anydatabase
- flexible asset pipline with grunt
- middleware 
- i18n 

**特性**
- MVC web 框架
- 基于 express 和 socket.io
- 数据驱动，面向服务架构，REST api 自动生成
- 支持任意数据库
- 使用 grunt 构建 asset
- 支持中间件
- 支持国际化

类似 Ruby on Rails 和 django
### who use
- [treeline](https://treeline.io/)
- [balderdash](http://balderdash.co/)

都是作者自己的产品
## [hapijs](http://hapijs.com/)

**feature**
- simple, original
- configuration over code
- need more plugin to support some feature

**特性**
- 简单，原始
- 很多特性都需要相应的插件来完成

框架简单，支持插件，适合在其上造轮子，开发应用需要首先找到合适的插件，否则仍然需要花时间开发常用的 web 特性
### who use
- http://revolt.tv/
- http://alphamantis.com/
- http://www.yahoo.com/
- [more](http://hapijs.com/community)
## [express](http://expressjs.com/)
- simple, explicit, easy

简单直接，容易上手，star 数最多
## [koajs](https://github.com/koajs/koa)

号称下一代 js web framewo，使用最新的 es6 语法和特性，如果对这些特性不是很深入了解，对其实际运作机制缺乏了解，难以掌握

**Comment by sereinlover** [comment]
写得很棒，让我更好地梳理了一遍interface。
