### ISSUE TITLE
mysql optimization : innodb tables

### ISSUE THREAD

**Issue by zhyq0826** [zhyq0826/zhyq0826.github.io#62]
http://dev.mysql.com/doc/refman/5.7/en/optimizing-innodb.html
# Innodb
## DDL

> For DDL operations on tables and indexes (CREATE, ALTER, and DROP statements), the most significant aspect for InnoDB tables is that creating and dropping secondary indexes is much faster in MySQL 5.5 and higher, than in MySQL 5.1 and before. See Section 15.13.1, “Overview of Online DDL” for details.
> 
> “Fast index creation” makes it faster in some cases to drop an index before loading data into a table, then re-create the index after loading the data.

创建和删除索引是比较快的，如果需要导入很大量的数据，可以考虑删除索引后导入，然后再创建

> Use TRUNCATE TABLE to empty a table, not DELETE FROM tbl_name. Foreign key constraints can make a TRUNCATE statement work like a regular DELETE statement, in which case a sequence of commands like DROP TABLE and CREATE TABLE might be fastest.

如果要清空表 使用 truncate table

> Because the primary key is integral to the storage layout of each InnoDB table, and changing the definition of the primary key involves reorganizing the whole table, always set up the primary key as part of the CREATE TABLE statement, and plan ahead so that you do not need to ALTER or DROP the primary key afterward

不要轻易的更改主键，最好在创建时确定好
## Storage Layout for InnoDB Tables

> Once your data reaches a stable size, or a growing table has increased by tens or some hundreds of megabytes, consider using the OPTIMIZE TABLE statement to reorganize the table and compact any wasted space. The reorganized tables require less disk I/O to perform full table scans. This is a straightforward technique that can improve performance when other techniques such as improving index usage or tuning application code are not practical.
> 
> OPTIMIZE TABLE copies the data part of the table and rebuilds the indexes. The benefits come from improved packing of data within indexes, and reduced fragmentation within the tablespaces and on disk. The benefits vary depending on the data in each table. You may find that there are significant gains for some and not for others, or that the gains decrease over time until you next optimize the table. This operation can be slow if the table is large or if the indexes being rebuilt do not fit into the buffer pool. The first run after adding a lot of data to a table is often much slower than later runs.

当数据量达到一定程度时，进行 optimize table.

> In InnoDB, having a long PRIMARY KEY (either a single column with a lengthy value, or several columns that form a long composite value) wastes a lot of disk space. The primary key value for a row is duplicated in all the secondary index records that point to the same row. (See Section 15.8.9, “Clustered and Secondary Indexes”.) Create an AUTO_INCREMENT column as the primary key if your primary key is long, or index a prefix of a long VARCHAR column instead of the entire column.

主键要短.

> Use the VARCHAR data type instead of CHAR to store variable-length strings or for columns with many NULL values. A CHAR(N) column always takes N characters to store data, even if the string is shorter or its value is NULL. Smaller tables fit better in the buffer pool and reduce disk I/O.
> 
> When using COMPACT row format (the default InnoDB format) and variable-length character sets, such as utf8 or sjis, CHAR(N) columns occupy a variable amount of space, but still at least N bytes.

变长值使用 varchar

> For tables that are big, or contain lots of repetitive text or numeric data, consider using COMPRESSED row format. Less disk I/O is required to bring data into the buffer pool, or to perform full table scans. Before making a permanent decision, measure the amount of compression you can achieve by using COMPRESSED versus COMPACT row format

如果表很大或者包含很多重复性的数据，考虑使用 compressed row format

**Comment by sheepstarli** [comment]
Create an AUTO_INCREMENT column as the primary key if your primary key is long, or index a prefix of a long VARCHAR column instead of the entire column.

这句话的后半句我没有太理解，不知道你是怎么理解的？

**Comment by zhyq0826** [comment]
@sheepstarli 主键或索引要短是理解这句话的前提。直接翻译过来就是，不要用一个特别长的 column 做主键，也不要用特别长的 varchar column 做索引，对于特别长的 column 可以考虑使用前缀索引，就是把 varchar 的一部分作为做索引。前缀索引见 https://dev.mysql.com/doc/refman/5.7/en/column-indexes.html#column-indexes-prefix

**Comment by sheepstarli** [comment]
@zhyq0826 看了一下你给的链接，然后又理解了一下。我觉得他那一段的意思是，如果主键比较长或者是一个组合起来比较长的主键，最好建一个自增的当做主键。因为其他所有的索引都会存储这个主键，以节省索引空间。至于使用prefix index可能一般都对业务有影响，在我这里就不考虑用了。
